"Scene Changes":
  - UnityProject/Assets/**/*.unity

"Scene: Almayer":
  - UnityProject/Assets/Scenes/Ships/Almayer.unity

"Scene: LV-624":
  - UnityProject/Assets/Scenes/MainStations/LV-624.unity

"Documentation":
  - docs/**/*

"Sprite Work":
  - UnityProject/Assets/Textures/**/*.png
  - UnityProject/Assets/Textures/**/*.PNG
  - AssetLibrary/**/*.png
  - AssetLibrary/**/*.PNG

"UI":
  - UnityProject/Assets/Scripts/UI/**/*
  - UnityProject/Assets/Scenes/UI/**/*
